[workspace]
members = [
  "http-api",
  "git-server",
  "service-init",
  "shared",
]

[patch.crates-io.librad]
git = "https://github.com/radicle-dev/radicle-link"
tag = "cycle/2022-03-01"

[patch.crates-io.git-ref-format]
git = "https://github.com/radicle-dev/radicle-link"
tag = "cycle/2022-03-01"

[patch.crates-io.radicle-source]
git = "https://github.com/radicle-dev/radicle-surf"
rev = "74b5fa5f620c21a0586050557329f915f795a34b"

[patch.crates-io.thrussh-encoding]
git = "https://github.com/FintanH/thrussh.git"
branch = "generic-agent"

[profile.release]
debug = true
