name: ci

on:
  push:
    branches:
     - master
     - build/*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to the container registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Build and push http-api
        id: http_api
        uses: docker/build-push-action@v2
        with:
          file: http-api/Dockerfile
          push: true
          tags: gcr.io/radicle-services/http-api:latest
      - name: Build and push org-node
        id: org_node
        uses: docker/build-push-action@v2
        with:
          file: org-node/Dockerfile
          push: true
          tags: gcr.io/radicle-services/org-node:latest
      - name: Build and push git-server
        id: git_server
        uses: docker/build-push-action@v2
        with:
          file: git-server/Dockerfile
          push: true
          tags: gcr.io/radicle-services/git-server:latest
